export const userActionTypes = {
	GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
	EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
	SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
	SIGNIN_FAILURE: 'SIGIN_FAILURE',
	CHECK_USER_SESSION: 'CHECK_USER_SESSION'
}

export default userActionTypes